version: "3"

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge

    ports:
      - "1433:1433"
    restart: always

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SqlExpress!"

  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:80"
      - "5001:443"
    restart: always
    environment:
      - DBHOST=db
      - DBPORT=1433
      - DBUSER=sa
      - DBNAME=assign1
      - DBPASSWORD=SqlExpress!
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup: